### ISSUE TITLE
Bug: The cells are considerably longer along the Z direction than XY

### ISSUE THREAD

**Issue by karpathyan** [walkersw/VTKwrite#2]
Hi, 
    Thanks for fixing the last bug. Currently, while we are trying to create a cell grid, the length of the unit cells is not uniform along the three directions. For example, in the example file `structured_ex1.py`, when we create a 6x6x2 grid, we should have a **cuboid** with dimensions, Length:Breadth: Height = 6:6:2. However, here we have a **cube**  with equal sided and the height of the cells (along Z direction) is 3 times that of along X, Y. Could you please fix this?
Thanks. 
Here is an image showing this:
![Cell_grid](https://user-images.githubusercontent.com/34363447/212684599-6ba72be4-2287-41bd-96cd-8da62237d855.png)

**Comment by walkersw** [comment]
This is something you can implement yourself.
